---
title: "Project"
author: "Mengxiao"
date: "2019/10/27"
output: pdf_document
---

```{r}
library(dplyr)
library(tidyr)
library(maps)

data <- read.csv('https://scads.eecs.wsu.edu/wp-content/uploads/2017/10/AM_strains_clean.csv', fileEncoding='utf-16', na.string = '?', sep='\t')
```
```{r echo=false}
location_levels = levels(data$Location.1)
location_levels = location_levels[2:length(location_levels)]

for (i in levels(data$Location.2)){
  if (i %in% location_levels){
    next
  }
  if (i == ''){
    next
  }
  location_levels[length(location_levels)+1] = i
}

for (i in levels(data$Location.3)){
  if (i %in% location_levels){
    next
  }
  if (i == ''){
    next
  }
  location_levels[length(location_levels)+1] = i
}
for (i in levels(data$Location.4)){
  if (i %in% location_levels){
    next
  }
  if (i == ''){
    next
  }
  location_levels[length(location_levels)+1] = i
}
for (i in levels(data$Location.5)){
  if (i %in% location_levels){
    next
  }
  if (i == ''){
    next
  }
  location_levels[length(location_levels)+1] = i
}
```
```{r}
location_levels
```
```{r}
mydata = data.frame(location_levels)
mydata$sets = rep(0, times=length(mydata))
for (i in 1:nrow(mydata)){
  mydata$sets[i] = 0
  for (j in 1:nrow(data)){
    temp = data[j,]
    if ((temp$Location.1 == location_levels[i]) | (temp$Location.2 == location_levels[i]) | (temp$Location.3 == location_levels[i]) |
        (temp$Location.4 == location_levels[i]) | (temp$Location.5 == location_levels[i])){
          mydata$sets[i] = mydata$sets[i]+1
        }
  }
}
mydata = mydata %>% 
  separate(location_levels, into=c("y", "x"), sep=",")
mydata$longitude = as.numeric(mydata$x)
mydata$latitude = as.numeric(mydata$y)
keys = c("longitude", "latitude", "sets")
mydata = mydata[keys]
mydata$country <- map.where('world', mydata$longitude, mydata$latitude)
mydata = mydata %>% separate(country, into=c("country", "city"), sep=":")
mydata$country[is.na(mydata$country)] <- "philippines"
mydata$country[mydata$country == "Taiwan"] <- "China"
keys[4] = c("country")
mydata = mydata[keys]

country_list = list()
country_list[1] = list("Global")
sum = 2
for (i in unique(mydata$country))
{
  country_list[sum] = list(i)
  sum = sum + 1
}
```


Start new part! Drawing map to see the locations.
```{r}
library(ggmap)
library(leaflet)
#myLocation <- c(-140, -50, 150, 70)
#myMap <- get_map(location=myLocation, source="stamen", maptype="terrain", zoom=3)
#ggmap(myMap)+geom_point(aes(x=longitude, y=latitude, size=sets), data=mydata, alpha=0.5, color="darkred")
```

Start new part! Use shiny to show the data.
```{r}
library(shiny)

ui <- fluidPage(
  
  #titlePanel("My Project!!!-Mengxiao"),
  fluidRow(
    sidebarLayout(
      
      sidebarPanel(
        
        sliderInput(inputId = "range",
                    label = "Range of strains:",
                    min = 1,
                    max = 60,
                    value = c(1, 60)),
        br(),
        selectInput(inputId = "selects",
                    label = "Countries",
                    choices = country_list, selected = "Global"),
        br(),
        textInput("text", h3("Strains"), 
                  value = "Enter text..."),
      ),
      
      # Main panel for displaying outputs ----
      mainPanel(
        
        # Output: Histogram ----
        plotOutput(outputId = "myPlot", width = "400px", height="400px"),
      )
    )
  ),
  fluidRow(
    plotOutput(outputId = "distPlot", width="100%", height="1000px")
  )
  
)
```
Server part.
```{r}
server <- function(input, output) {
  
  # Histogram of the Old Faithful Geyser Data ----
  # with requested number of bins
  # This expression that generates a histogram is wrapped in a call
  # to renderPlot to indicate that:
  #
  # 1. It is "reactive" and therefore should be automatically
  #    re-executed when inputs (input$bins) change
  # 2. Its output type is a plot  
  output$myPlot <-  renderPlot({
    plot(mydata$sets)
  })
  
  output$distPlot <- renderPlot({
    
    x    <- faithful$waiting
    country <- input$selects
    sequences <- input$text
    range <- input$range
    
    myLocation <- c(-140, -50, 150, 70)
    myMap <- get_map(location=myLocation, source="stamen", maptype="terrain", zoom=3)
    if (country == "Global"){
      newdata <- mydata
    }
    else{
      newdata <- mydata[mydata$country == country, ]
    }
    newdata <- newdata[mydata$sets<=input$range[2]&mydata$sets>=input$range[1], ]
    
    if (sequences != '' & sequences != "Enter text..."){
      if (sum(data$Sequence == sequences)){
        firstdata = data[data$Sequence == sequences, ]
        newlocations = data.frame(
          latitude = rep(0, 5),
          longitude = rep(0, 5),
          sets = rep(0, 5))
        newlocations[1,1:2] = data.frame(firstdata$Location.1) %>% separate(firstdata.Location.1, into=c("latitude", "longitude"), sep=",")
        newlocations[2,1:2] = data.frame(firstdata$Location.2) %>% separate(firstdata.Location.2, into=c("latitude", "longitude"), sep=",")
        newlocations[3,1:2] = data.frame(firstdata$Location.3) %>% separate(firstdata.Location.3, into=c("latitude", "longitude"), sep=",")
        newlocations[4,1:2] = data.frame(firstdata$Location.4) %>% separate(firstdata.Location.4, into=c("latitude", "longitude"), sep=",")
        newlocations[5,1:2] = data.frame(firstdata$Location.5) %>% separate(firstdata.Location.5, into=c("latitude", "longitude"), sep=",")
        c = list(1,2,3,4,5)
        for (i in c){
          if (is.na(newlocations[i, 2])){
            newlocations[i, 3] = 0
          }
          else{
            newlocations[i, 3] = 1
          }
        }
        newdata = newlocations
        newdata$longitude = as.numeric(newdata$longitude)
        newdata$latitude = as.numeric(newdata$latitude)
      }
    }
    ggmap(myMap)+geom_point(aes(x=longitude, y=latitude, size=sets, colour = cut(sets, c(0, 20, 40, 60))), data = newdata, alpha=0.8)+scale_colour_manual(name = "sets",
                     values = c("green", "red", "black"),
                     labels = c("<= 20", "20 < sets <= 40", "> 40"))+scale_size_continuous(range=c(4, 15))
  }) 

}
```
Start server.
```{r}
shinyApp(ui = ui, server = server)
```